version: "3.5"
services:

  db:
    image: mysql/mysql-server:8.0.23
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=emp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
    ports:
      - 3306:3306

  web:
    image: viniciusferreirac/vinicius-elo
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - DATABASE_ROOT_PASSWORD=12345678
