apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql/mysql-server:8.0.23
          env:
            - name: MYSQL_DATABASE
              value: emp
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsenha
                  key: dbsenha
          ports:
            - containerPort: 3306
              protocol: TCP
