apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://10.108.16.81:8200"
      path: "dbcred"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-policy-token"
          key: "token"
  namespaceSelector:
    matchNames:
      - nomequeeuquero
