apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dbsenha-external
  namespace: nomequeeuquero
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-backend  # Nome correto do ClusterSecretStore
    kind: ClusterSecretStore
  target:
    name: dbsenha  # Nome do segredo no Kubernetes
  data:
    - secretKey: dbsenha  # Nome da chave no Kubernetes
      remoteRef:
        key: dbcred/senha  # Caminho correto para o segredo no Vault
        property: senhadb  # Propriedade correta no Vault (alterado para "senhadb")
